export const featureDefaults: Record<string, boolean> = {
  'analysis.enabled': true,
  'analysis.compare': true,
  'analysis.insights': true,
  'analysis.timeline': true,
  'analysis.persistResults': false,
  'analysis.fundIndexMatrix': true,
  'analysis.incrementalAggregates': true,
  'analysis.fundReport': true,
  'analysis.fundReportProgressive': true,
  'analysis.peerComparison': true,
  'ui.landingPage': true,
  'ui.methodPage': true,
  // Analyze and Compare are dormant; the fund report is the only analysis surface.
  // The analysis.* flags stay on because the report's charts still call /api/analysis.
  'ui.dashboardPage': false,
  'ui.comparePage': false,
  'ui.commandPalette': true,
  'ui.favorites': true,
  'ui.recentAnalyses': true,
  'ui.themeToggle': true,
  'ui.statCards': true,
  'ui.rollingReturnsPanel': true,
  'ui.fundIndexMatrixTable': true,
  'ui.riskMeter': true,
  'ui.insightsPanel': true,
  'ui.performanceTimeline': true,
  'ui.additionalCharts': true,
  'ui.exportPdf': true,
  'ui.share': true,
  'ui.fundReportPage': true,
}
