sonar.projectKey=mutual-funds-analyzer
sonar.projectName=Mutual Funds Analyzer
sonar.sources=backend/src/main/java,src
sonar.tests=backend/src/test/java
sonar.java.binaries=backend/target/classes
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=**/dist/**,**/node_modules/**,**/target/**
